version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

  app:
    build:
      context: ./node
    container_name: app
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://db:3306",
        "-timeout",
        "30s",
        "sh",
        "-c",
        "npm install && node index.js",
      ]
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
